### ISSUE TITLE
[Windows] Consider adding other store names than `"ROOT"` 

### ISSUE THREAD

**Issue by ginger51011** [rustls/rustls-native-certs#131] opened 2024-09-05 13:46 UTC
Hello, thanks for the good work on rustls!

I'm writing from inside the corporate world where certificates are pushed out on user machines, much like #22. I recently found out that while rustls-native-certs can detect certificates in the `Root` certificate store, it fails to detect all that are needed in my environment.

I can open a PR for adding some other stores that are required for my use case, but I wanted to ask the question if it is desirable? Basically a change would look like this (in my case only `CA` needs to be added, but the others might be a good idea):

```rust
// windows.rs
/// See <https://learn.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/wcf/certificate-of-clientcertificate-element?redirectedfrom=MSDN#attributes>
const CERTIFICATE_STORE_NAMES: &[&str] = [
    "My",   // -> Certificate store for personal certificates
    "Root", // -> Trusted Root Certification Authorities
    "Trust", // -> I'm honestly not quite sure; I believe trusted third parties. There doesn't seem to be a good list.
    "CA",   // -> Intermediate Certification Authorities
];

pub fn load_native_certs() -> CertificateResult {
    let mut result = CertificateResult::default();

    for store_name in CERTIFICATE_STORE_NAMES {
        let current_user_store = match CertStore::open_current_user(store_name) {
            Ok(store) => store,
            Err(err) => {
                result.os_error(
                    err.into(),
                    format!("failed to open current user certificate store '{store_name}'"),
                );
                return result;
            }
        };

        for cert in current_user_store.certs() {
            if usable_for_rustls(cert.valid_uses().unwrap()) && cert.is_time_valid().unwrap() {
                result
                    .certs
                    .push(CertificateDer::from(cert.to_der().to_vec()));
            }
        }
    }

    result
}
```

The docs for [`CertStore::open_current_user`](https://docs.rs/schannel/latest/schannel/cert_store/struct.CertStore.html#method.open_current_user) mentions the store names I have included here, and the [source](https://learn.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/wcf/certificate-of-clientcertificate-element?redirectedfrom=MSDN#attributes) above the `CERTIFICATE_STORE_NAMES` go into some detail.

**Comment by cpu** [comment] 2024-09-05 15:36
Out of curiosity, does [`rustls-platform-verifier`](https://github.com/rustls/rustls-platform-verifier) pick up your custom roots without issue?

**Comment by ginger51011** [comment] 2024-09-06 09:29
@cpu I wrote the following small program to test, and in my environment passing `PV=1` (using rustls-platform-verifier) passes, but not doing so (using rustls-native-certs) fails (assuming I am using things correctly; my real use-case is using rustls via the reqwest `rustls-tls-native-roots` feature). Perhaps this is a reqwest issue?

The test was done using an internal service on SERVER signed by a specific certificate `CORP-1`, signed by `CORP-ROOT`. `CORP-ROOT` is available in the `Root` cert store, but `CORP-1` is not.

```rust
use std::io::{Write, Read};
use std::sync::Arc;
use rustls::ClientConfig;
use rustls_platform_verifier;
use rustls_native_certs;

fn main() {
    let pv = std::env::var("PV");
    let server = std::env::var("SERVER").unwrap();

    let config = if let Ok("1") = pv.as_deref() {
        println!("Using platform verifier");
        ClientConfig::builder()
            .dangerous()
            .with_custom_certificate_verifier(Arc::new(rustls_platform_verifier::Verifier::new()))
            .with_no_client_auth()
    } else {
        println!("Using native tls verifier (change by passing setting PV=1)");
        let mut roots = rustls::RootCertStore::empty();
        let native_certs = rustls_native_certs::load_native_certs().unwrap();
        for cert in native_certs {
            roots.add(cert).unwrap();
        }

        ClientConfig::builder()
            .with_root_certificates(roots)
            .with_no_client_auth()
    };
    let rc_config = Arc::new(config);
    let host = server.clone().try_into().unwrap();
    let mut client = rustls::ClientConnection::new(rc_config, host).unwrap();

    let mut socket = std::net::TcpStream::connect(&format!("{server}:443")).unwrap();
    let mut stream = rustls::Stream::new(&mut client, &mut socket); // Create stream

    stream
    .write(b"GET / HTTP/1.1\r\nConnection: close\r\n\r\n")
    .unwrap();
    let mut plaintext = Vec::new();
    stream.read_to_end(&mut plaintext).unwrap();
    std::io::stdout().write_all(&plaintext).unwrap();
}
```

**Comment by djc** [comment] 2024-09-06 12:06
Specifically for Windows (and macOS) I think the platform verifier crate always provides a better solution so unless you have a specific use case for the particular functionality in native-certs, I think you should just use that instead.

**Comment by cpu** [comment] 2024-09-06 13:56
> (using rustls-platform-verifier) passes,

Thanks for testing! That's good news.

>  my real use-case is using rustls via the reqwest rustls-tls-native-roots feature). Perhaps this is a reqwest issue?

I think the right fix is for `reqwest` to adopt `rustls-platform-verifier`. There's an outstanding issue to watch for this: https://github.com/seanmonstar/reqwest/issues/2159

> Specifically for Windows (and macOS) I think the platform verifier crate always provides a better solution so unless you have a specific use case for the particular functionality in native-certs, I think you should just use that instead.

Agreed.

**Comment by ginger51011** [comment] 2024-09-06 15:45
> > (using rustls-platform-verifier) passes,
> 
> Thanks for testing! That's good news.
> 
> >  my real use-case is using rustls via the reqwest rustls-tls-native-roots feature). Perhaps this is a reqwest issue?
> 
> I think the right fix is for `reqwest` to adopt `rustls-platform-verifier`. There's an outstanding issue to watch for this: https://github.com/seanmonstar/reqwest/issues/2159
> 
> > Specifically for Windows (and macOS) I think the platform verifier crate always provides a better solution so unless you have a specific use case for the particular functionality in native-certs, I think you should just use that instead.
> 
> Agreed.

Thanks for linking that issue, it does indeed seem like the solution. I do believe that's the behaviour I needed all along.

I'm gonna check a bit more next week, but I simply did not know rustls-platform-verifier existed.

**Comment by djc** [comment] 2024-09-07 08:02
> I think the right fix is for `reqwest` to adopt `rustls-platform-verifier`. There's an outstanding issue to watch for this: [seanmonstar/reqwest#2159](https://github.com/seanmonstar/reqwest/issues/2159)

To be clear, you can use reqwest with the platform verifier crate today:

```rust
Client::builder()
.use_preconfigured_tls(
     rustls_platform_verifier::tls_config_with_provider(Arc::new(
           aws_lc_rs::default_provider(),
     ))
     .expect("failed to initialize pre-configured rustls backend"),
)
```

**Comment by cpu** [comment] 2024-09-07 12:46
> you can use reqwest with the platform verifier crate today:

Thanks for clarifying, that's a good call out. I meant just in terms of offering features to do this out-of-box ala `rustls-tls-native-roots` and `native-roots`.

**Comment by cpu** [comment] 2024-09-17 16:14
I'm going to close this issue since I think we've reached a conclusion where `rustls-platform-verifier` is confirmed to work and we're generally in favour of investing resources in that repo vs adding more complexity to `rustls-native-certs`. If I'm mistaken and folks believe there's more to discuss here we can re-open.

Thanks!

**Closed by cpu** 2024-09-17 16:14 UTC
