### ISSUE TITLE
Can't find certs in Android device

### ISSUE THREAD

**Issue by laiyi55** [rustls/rustls-native-certs#90] opened 2024-01-24 08:42 UTC
```
        let tls = rustls::ClientConfig::builder()
                .with_native_roots()?
                .with_no_client_auth();


        // Prepare the HTTPS connector
        let https = hyper_rustls::HttpsConnectorBuilder::new()
            .with_tls_config(tls)
            .https_or_http()
            .enable_http1()
            .build();
```

logcat:
with_native_roots processed 0 valid and 0 invalid certs
no valid native root CA certificates found

How can I fix this problem?

**Comment by djc** [comment] 2024-01-24 08:55
I've moved this issue to the rustls-native-certs repo, as that is the crate that is doing the certificate discovery in the setup you've described. I'm not sure this has ever been tested on Android? I think [rustls-platform-verifier](https://crates.io/crates/rustls-platform-verifier) might be a better solution here, but there's no integration with hyper-rustls yet.

**Comment by ctz** [comment] 2024-01-24 09:06
I think this is a duplicate of #3

**Closed by ctz** 2024-01-24 09:06 UTC
